services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      # We override the REDIS_URL to point to the local redis container below
      # for local development without needing an internet connection to Upstash
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
